apiVersion: v1
kind: Service
metadata:
  name: {{ include "oktetotest.fullname" . }}
  labels:
    {{- include "oktetotest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: { { .Values.port } }
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "oktetotest.selectorLabels" . | nindent 4 }}
