# This is a basic workflow to help you get started with Actions

name: Okteto Preview

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  destroy-environment:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Destroy preview environment
      continue-on-error: true
      uses: okteto/destroy-preview@master
      with:
        name: pr-${{ github.event.number }}-sswastioyono18


  preview:
    needs: destroy-environment
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy preview environment - feature branch
        uses: okteto/deploy-preview@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: pr-${{ github.event.number }}-sswastioyono18
          scope: personal
          timeout: 15m
