# preview-closed.yaml
on:
  pull_request:
    types:
      - closed

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Destroy preview environment
        uses: okteto/destroy-preview@master
        with:
          name: pr-${{ github.event.number }}-sswastioyono18

  destroy-master-environment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Destroy preview environment
        continue-on-error: true
        uses: okteto/destroy-preview@master
        with:
          name: master-sswastioyono18

  deploy-master:
    needs: destroy-master-environment
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy preview environment - master branch
        uses: okteto/deploy-preview@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: master-sswastioyono18
          scope: personal
          timeout: 15m