# file: .github/workflows/preview.yaml
on:
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest
  steps:
    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Deploy preview environment
      uses: okteto/deploy-preview@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: pr-${{ github.event.number }}-cindylopez
        scope: personal
        timeout: 15m